### ISSUE TITLE
JSON gem not found with v2 of licensed

### ISSUE THREAD

**Issue by lcpriest** [github/licensed#143]
Uncertain what causes it - I migrated to licensed v2 and it was unable to find certain gems (json 2.1.0 in this case).

Example app: https://github.com/lcpriest/bug-demo-licensed
Ruby version 2.5.1

### Steps to reproduce:
- 1 Run `bundle install`
- 2 Run `licensed cache`

### Expected outcome
All licenses would be cached

### Actual outcome
Some licenses were cached but it threw the following error

```
  * Errors:
    * Test-app.bundler.json
      - expected dependency path /Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/json-2.1.0 does not exist
```

**Comment by jonabc** [comment]
Thanks for the report.  I'll take a look, thank you very much for providing a demo project!

**Comment by jonabc** [comment]
Long winded explanation, followed by how to address this.

For background context, ruby ships with a number of standard, default gems of which `json` is one.  These gems are not installed in the same manner as the gems that come from `bundle install`, most notably they don't necessarily have gem directories and none of them include any documentation (including the `LICENSE` files that this tool is looking for).

What's happening is that `bundle install` is installing gems to the system location, and you don't have a version requirement on the `json` gem that would disqualify using the standard default `json` gem.  This causes bundler to use the default gem rather than download and install a full gem.  

Since bundler is then using the default gem (which doesn't have a gem directory), the path that's reported by `Bundler::StubSpecification#gem_dir` doesn't exist, leading to this reported error.

The above scenario also occurred in licensed v1, however the path not existing on the local disk didn't raise an error.

I'm planning to fix this by treating a non-existent path as a warning instead of an error.  That should allow the rest of the license data to be cached, the command will "succeed" while still printing a message to the user 👍

**Comment by jonabc** [comment]
As an aside, I believe `bundle install --path vendor/gems` will also cause this error to go away

**Comment by lcpriest** [comment]
I really appreciate the deep dive! That all makes sense and I want to thank you for the work you are doing - it's genuinely very useful; the v2 release had a *significantly* higher license discovery rate and a higher designation rate also (a lot less mit licenses marked as `other` for example.)

Thank you for that!
