### ISSUE TITLE
Additional variations of common licenses

### ISSUE THREAD

**Issue by schmidtw** [github/licensed#357]
I'm not sure where you want license misses, but here are a few I found.  Several looked like either simple whitespace changes or missing '*' values.

```
    - emperror.dev/errors                       # MIT
    - github.com/magiconair/properties          # bsd-2-clause
    - github.com/jtacoma/uritemplates           # bsd-3-clause
    - github.com/pmezard/go-difflib             # bsd-3-clause (unmaintained)
    - github.com/samuel/go-zookeeper            # bsd-3-clause
    - go.uber.org/dig                           # MIT
    - go.uber.org/dig/internal/dot              # MIT
    - golang.org/x/sys/internal/unsafeheader    # bsd-3-clause
    - golang.org/x/sys/unix                     # bsd-3-clause
    - gopkg.in/ini                              # apache-2.0
    - gopkg.in/yaml.v2                          # apache-2.0
    - github.com/gorilla/mux                    # bsd-3-clause
```

This tool is really great.  Thanks for making it & the GH Action!

**Comment by jonabc** [comment]
:wave: sorry I missed you opening this issue @schmidtw, and thanks for the praise 🙇 

github/licensed doesn't actually do any license parsing or classification itself, it uses [licensee](https://github.com/licensee/licensee) for that.  I'd recommend opening an issue in that repo because there's not too much that this tool specifically can handle to fix it.

I'm going to close this for now, but please reopen if you feel there's more to be done here 🙏
