### ISSUE TITLE
[npm] Troubles getting licenses for some dependencies

### ISSUE THREAD

**Issue by jgeurts** [github/licensed#358]
Hi @jonabc, I'm curious if you can help with why some dependencies are showing as "other" when they seem to have licenses specified in their package.json file. [A repository reproducing the behavior](https://github.com/jgeurts/licensed_issue/tree/single_root_app) is available as are [licensed results](https://github.com/jgeurts/licensed_issue/runs/2505243187?check_suite_focus=true).

Apologies for the weird reproduction repo, I originally thought this issue had to do with multiple apps in sub folders. 

Please let me know if I can provide any other details!

**Comment by jonabc** [comment]
:wave: @jgeurts "other" means that license contents were found, but for some reason could not be automatically parsed by the license parsing library this tool uses, [licensee](https://github.com/licensee/licensee).  Usually this is because 
1. the license text is different enough from the standard license text that it isn't matched
2. more than one license was detected, or a license file contains contents from multiple licenses
3. contents were found in other legal-type files that doesn't match a license (this is seen a bunch when additional grants are given beyond the license chosen)

In many cases these are easy to detect and correct through human review, and it's encouraged in these cases to manually change `license: other` to `license: <other correct file>`.  licensed will maintain the license classification as long as the detected license contents remain the same and license contents don't change too often so for most dependencies this is a one-time cost.

To see what's failing though you'd need access to the cached metadata files.  A normal workflow using licensed would have `licensed cache` generated metadata files committed into the repo.  If you haven't seen it, [jonabc/licensed-ci](https://github.com/jonabc/licensed-ci) exists to make running licensed in GitHub Actions easy.  It will cache and commit updates, and succeed/fail based on the results of `licensed status`.

I'm going to close this issue because there's nothing actionable here, but feel free to keep the conversation going if you have any additional questions 🙇

**Comment by dbimhoff** [comment]
While it isn't hard to go in and check these manually, when you have 80 errors in multiple repos it becomes quite the time consuming task. Is there any good way to solve this?

**Comment by jonabc** [comment]
@dbimhoff unfortunately the only option at the moment is to manually update each dependency's file.  licensed doesn't perform the license classification itself, that's from [licensee/licensee](https://github.com/licensee/licensee), and I don't think this tool should be automatically overriding any license determination from licensee.

That said, I've also felt this pain and I'm very open to finding room for improvement.  Given the constraint that licensed shouldn't re-implement or override logic from licensee, do you have any suggestions or ideas on making this easier?

**Comment by mlinksva** [comment]
I took a quick look to see whether any of the [failures](https://github.com/jgeurts/licensed_issue/runs/2505243187?check_suite_focus=true) should be fixed in licensee, and unfortunately there aren't any -- in each case there's text present that licensee can't reasonably understand, and because it is conservative (preferring false negatives to positives) it makes sense to return other/NOASSERTION.

Completely idle thought, perhaps licensed should optionally consult the ClearlyDefined API? I'm not intimately familiar, but I understand that sometimes it will say that a package has a declared license that licensee cannot, because programs that it runs in addition to licensee (scancode, IIRC) or human curation make a license determination. For example, https://api.clearlydefined.io/definitions/npm/npmjs/-/glob/7.0.6

**Comment by jgeurts** [comment]
I know an automated workaround/fix would be ideal, but I’m thinking that I’ll submit a PR to each repo that has an unusual license. In my case, there were only a handful of projects with licenses that did not parse correctly. 

I imagine that I will hit stale or dead repositories, but I’ll give it a shot and maybe help others in the process 🤷

**Comment by jonabc** [comment]
> Completely idle thought, perhaps licensed should optionally consult the ClearlyDefined API? I'm not intimately familiar, but I understand that sometimes it will say that a package has a declared license that licensee cannot, because programs that it runs in addition to licensee (scancode, IIRC) or human curation make a license determination.

👍  ClearlyDefined has expressed interest in begin a source for license information with this tool so we'll see how that goes.
