### ISSUE TITLE
use yarn / npm license field?

### ISSUE THREAD

**Issue by sterlingwes** [github/licensed#390]
Hello! Thanks for this great tool 🙏 

I noticed a number of NPM / yarn dependencies are reporting `license: other` in their cache data / results. In most cases these dependencies have the correct license code [defined in the license key](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license) of their package.json, and it seems that the underlying licensee gem is just not able to match the text of the license.

One example is [this lib](https://github.com/sideway/address/blob/cd413d2917bf0aa7d4a029f83cdaf13de1e44966/package.json#L29) which uses a slight variation of the BSD-3 license. It's substantially the same license but I could see why the matcher would fail on the third clause in particular.

Would it be reasonable to have NPM / yarn sources fallback to the license field of the package.json in these scenarios vs. reporting `other` in these scenarios?

**Comment by jonabc** [comment]
:wave: hi @sterlingwes.  Generally speaking, the purpose of this tool is to source and locate dependency project information from different package managers and pass that information to licensee for license determination.  Licensed makes no attempt to perform license classification and I'm hesitant to start adding that in because it makes the tool more complex and blurs the lines of what this tool does vs what licensee does.

Licensee does have documentation on [what files and content they look at](https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md) to make a license determination.  There is a mention of enabling package manager file detection as an optional supplemental information source, which is [enabled on all licensed-source dependency projects](https://github.com/github/licensed/blob/1ac9593970dc69eb310f439f32a6642f91f1eb9c/lib/licensed/dependency.rb#L40).

If you or another human are able to make a classification for a project where the tool is not, you can [update the `license: other` classification manually](https://github.com/github/licensed/blob/master/docs/commands/status.md#license-needs-review).  The classification will persist through version upgrades until licensee determines that the license contents have changed.  The goal of that functionality is to help make this scenario easier.

I'm going to close this as I'm not sure there's anything actionable for licensed on this request at this point in time.

**Comment by sterlingwes** [comment]
Thanks Jon for the detailed response! That's interesting that you have `detect_packages` enabled but I'm still seeing `other` in this case. I'll dig into that more I guess, but your distinction between license & licensee in terms of domains of responsibility makes sense to me.
